export const HAIR_TECHS = [
  { name: 'Maya K', city: 'San Jose' },
  { name: 'Brielle J', city: 'Cupertino' },
  { name: 'Aaliyah R', city: 'Fremont' },
  { name: 'Jasmine M', city: 'Oakland' },
  { name: 'Nia T', city: 'Palo Alto' },
  { name: 'Selena P', city: 'Sunnyvale' },
  { name: 'Tiana B', city: 'Santa Clara' },
  { name: 'Priya S', city: 'Milpitas' },
  { name: 'Kayla D', city: 'Mountain View' },
  { name: 'Amara C', city: 'Redwood City' },
  { name: 'Lexi H', city: 'San Francisco' },
  { name: 'Simone V', city: 'Berkeley' },
  { name: 'Renee L', city: 'Dublin' },
  { name: 'Kiara W', city: 'Hayward' },
  { name: 'Anika R', city: 'Pleasanton' },
  { name: 'Mariah G', city: 'Walnut Creek' },
  { name: 'Jade F', city: 'Campbell' },
  { name: 'Alina M', city: 'Los Gatos' },
  { name: 'Zara N', city: 'San Mateo' },
  { name: 'Tessa B', city: 'Santa Rosa' },
]

export const NAIL_TECHS = [
  { name: 'Bella Nails', city: 'San Jose' },
  { name: 'Kay’s Claws', city: 'Cupertino' },
  { name: 'Mia Acrylics', city: 'Fremont' },
  { name: 'Luxe Nails by Ari', city: 'Oakland' },
  { name: 'Nina Nail Studio', city: 'Palo Alto' },
  { name: 'Glossed by Gia', city: 'Sunnyvale' },
  { name: 'Tori Tips', city: 'Santa Clara' },
  { name: 'Pink Set Studio', city: 'Milpitas' },
  { name: 'Nailed by Liv', city: 'Mountain View' },
  { name: 'Crystal Claws', city: 'Redwood City' },
  { name: 'The Nail Plug', city: 'San Francisco' },
  { name: 'Designs by Dee', city: 'Berkeley' },
  { name: 'Aura Nails', city: 'Dublin' },
  { name: 'Kiki’s Sets', city: 'Hayward' },
  { name: 'Soft Gel Studio', city: 'Pleasanton' },
  { name: 'Mani Muse', city: 'Walnut Creek' },
  { name: 'Angel Nails Co.', city: 'Campbell' },
  { name: 'Pearl Polish', city: 'Los Gatos' },
  { name: 'Chrome Studio', city: 'San Mateo' },
  { name: 'Ivy Nail Bar', city: 'Santa Rosa' },
]

export const LASH_TECHS = [
  { name: 'Lashes by Layla', city: 'San Jose' },
  { name: 'Wink Studio', city: 'Cupertino' },
  { name: 'Lash Luxe', city: 'Fremont' },
  { name: 'Bella Blink', city: 'Oakland' },
  { name: 'Vibe Lash Co.', city: 'Palo Alto' },
  { name: 'The Lash Room', city: 'Sunnyvale' },
  { name: 'Dreamy Lashes', city: 'Santa Clara' },
  { name: 'Glow Lash Studio', city: 'Milpitas' },
  { name: 'Lash Lab by Mia', city: 'Mountain View' },
  { name: 'Ari’s Lash Bar', city: 'Redwood City' },
  { name: 'Flutter & Co.', city: 'San Francisco' },
  { name: 'Blink Beauty', city: 'Berkeley' },
  { name: 'Doll Eye Studio', city: 'Dublin' },
  { name: 'Lash Haven', city: 'Hayward' },
  { name: 'Nova Lash Bar', city: 'Pleasanton' },
  { name: 'Pretty Wink Studio', city: 'Walnut Creek' },
  { name: 'Lash Lounge by Jade', city: 'Campbell' },
  { name: 'Soft Glam Lashes', city: 'Los Gatos' },
  { name: 'Angel Lash Co.', city: 'San Mateo' },
  { name: 'Luxe Blink Studio', city: 'Santa Rosa' },
]
